export const Exercises = [
    {
        name: "Bench Press",
        type: "strength",
        description: "A compound exercise that targets the chest, shoulders, and triceps.",
        // image: require("../assets/exercises/bench-press.png"),
        muscleGroups: ["chest", "shoulders", "triceps"],
        difficulty: "intermediate",
        id: "1",
    },
    {
        name: "Squats",
        type: "strength",
        description: "A compound exercise that targets the quadriceps, hamstrings, and glutes.",
        // image: require("../assets/exercises/squats.png"),
        muscleGroups: ["legs", "glutes"],
        difficulty: "intermediate",
        id: "2",
    },
    {
        name: "Deadlifts",
        type: "strength",
        description: "A compound exercise that targets the back, glutes, and hamstrings.",
        // image: require("../assets/exercises/deadlifts.png"),
        muscleGroups: ["back", "legs", "glutes"],
        difficulty: "advanced",
        id: "3",
    },
    {
        name: "Overhead Press",
        type: "strength",
        description: "A compound movement targeting the shoulders and triceps.",
        // image: require("../assets/exercises/overhead-press.png"),
        muscleGroups: ["shoulders", "triceps"],
        difficulty: "intermediate",
    },
    {
        name: "Barbell Row",
        type: "strength",
        description: "A compound back exercise that also engages the biceps.",
        // image: require("../assets/exercises/barbell-row.png"),
        muscleGroups: ["back", "biceps"],
        difficulty: "intermediate",
    },
    {
        name: "Pull-Ups",
        type: "strength",
        description: "A bodyweight exercise that targets the upper back and biceps.",
        // image: require("../assets/exercises/pull-ups.png"),
        muscleGroups: ["back", "biceps"],
        difficulty: "advanced",
    },
    {
        name: "Push-Ups",
        type: "strength",
        description: "A bodyweight exercise that targets the chest, shoulders, and triceps.",
        // image: require("../assets/exercises/push-ups.png"),
        muscleGroups: ["chest", "shoulders", "triceps"],
        difficulty: "beginner",
    },
    {
        name: "Dumbbell Lunges",
        type: "strength",
        description: "A unilateral lower-body exercise focusing on the quads, hamstrings, and glutes.",
        // image: require("../assets/exercises/dumbbell-lunges.png"),
        muscleGroups: ["legs", "glutes"],
        difficulty: "intermediate",
    },
    {
        name: "Lat Pulldown",
        type: "strength",
        description: "An upper-body machine exercise that targets the latissimus dorsi.",
        // image: require("../assets/exercises/lat-pulldown.png"),
        muscleGroups: ["back", "biceps"],
        difficulty: "beginner",
    },
    {
        name: "Leg Press",
        type: "strength",
        description: "A machine-based exercise that targets the quadriceps, hamstrings, and glutes.",
        // image: require("../assets/exercises/leg-press.png"),
        muscleGroups: ["legs", "glutes"],
        difficulty: "beginner",
    },
    {
        name: "Incline Dumbbell Press",
        type: "strength",
        description: "A variation of the bench press that emphasizes the upper chest and shoulders.",
        // image: require("../assets/exercises/incline-dumbbell-press.png"),
        muscleGroups: ["chest", "shoulders", "triceps"],
        difficulty: "intermediate",
    },
    {
        name: "Tricep Dips",
        type: "strength",
        description: "A bodyweight exercise that targets the triceps and shoulders.",
        // image: require("../assets/exercises/tricep-dips.png"),
        muscleGroups: ["triceps", "shoulders"],
        difficulty: "intermediate",
    },
    {
        name: "Bicep Curls",
        type: "strength",
        description: "An isolation exercise focusing on the biceps.",
        // image: require("../assets/exercises/bicep-curls.png"),
        muscleGroups: ["biceps"],
        difficulty: "beginner",
    },
    {
        name: "Calf Raises",
        type: "strength",
        description: "An exercise that targets the calf muscles.",
        // image: require("../assets/exercises/calf-raises.png"),
        muscleGroups: ["calves"],
        difficulty: "beginner",
    },
    {
        name: "Chest Fly",
        type: "strength",
        description: "An isolation movement for the chest using dumbbells or a machine.",
        // image: require("../assets/exercises/chest-fly.png"),
        muscleGroups: ["chest"],
        difficulty: "beginner",
    },
    {
        name: "Face Pulls",
        type: "strength",
        description: "An exercise that targets the rear delts and upper back.",
        // image: require("../assets/exercises/face-pulls.png"),
        muscleGroups: ["shoulders", "back"],
        difficulty: "beginner",
    },
    {
        name: "Hammer Curls",
        type: "strength",
        description: "A variation of bicep curls that also targets the forearms.",
        // image: require("../assets/exercises/hammer-curls.png"),
        muscleGroups: ["biceps", "forearms"],
        difficulty: "beginner",
    },
    {
        name: "Romanian Deadlift",
        type: "strength",
        description: "A variation of the deadlift focusing on the hamstrings and glutes.",
        // image: require("../assets/exercises/romanian-deadlift.png"),
        muscleGroups: ["hamstrings", "glutes", "lower back"],
        difficulty: "intermediate",
    },
    {
        name: "Seated Chest Press",
        type: "strength",
        description: "A machine-based chest press that targets the chest, shoulders, and triceps.",
        // image: require("../assets/exercises/seated-chest-press.png"),
        muscleGroups: ["chest", "shoulders", "triceps"],
        difficulty: "beginner",
    },
    {
        name: "Cable Lateral Raise",
        type: "strength",
        description: "An isolation exercise for the lateral deltoids using a cable machine.",
        // image: require("../assets/exercises/cable-lateral-raise.png"),
        muscleGroups: ["shoulders"],
        difficulty: "intermediate",
    },
    {
        name: "Preacher Curl",
        type: "strength",
        description: "An isolation curl done on a preacher bench to target the biceps.",
        // image: require("../assets/exercises/preacher-curl.png"),
        muscleGroups: ["biceps"],
        difficulty: "beginner",
    },
    {
        name: "Cable Tricep Pushdown",
        type: "strength",
        description: "A cable machine exercise that isolates the triceps.",
        // image: require("../assets/exercises/cable-tricep-pushdown.png"),
        muscleGroups: ["triceps"],
        difficulty: "beginner",
    },
    {
        name: "Leg Curl Machine",
        type: "strength",
        description: "An isolation exercise targeting the hamstrings using a machine.",
        // image: require("../assets/exercises/leg-curl.png"),
        muscleGroups: ["hamstrings"],
        difficulty: "beginner",
    },
    {
        name: "Leg Extension Machine",
        type: "strength",
        description: "An isolation exercise that targets the quadriceps using a seated machine.",
        // image: require("../assets/exercises/leg-extension.png"),
        muscleGroups: ["quadriceps"],
        difficulty: "beginner",
    },
    {
        name: "Smith Machine Squat",
        type: "strength",
        description: "A guided barbell squat performed on the Smith machine, targeting the lower body.",
        // image: require("../assets/exercises/smith-machine-squat.png"),
        muscleGroups: ["legs", "glutes"],
        difficulty: "intermediate",
    },
    {
        name: "Seated Row Machine",
        type: "strength",
        description: "A machine exercise that targets the upper and mid-back.",
        // image: require("../assets/exercises/seated-row.png"),
        muscleGroups: ["back", "biceps"],
        difficulty: "beginner",
    },
    {
        name: "Hack Squat Machine",
        type: "strength",
        description: "A machine-based lower-body exercise that emphasizes the quads.",
        // image: require("../assets/exercises/hack-squat.png"),
        muscleGroups: ["quadriceps", "glutes"],
        difficulty: "intermediate",
    },
    {
        name: "Pec Deck (Chest Fly Machine)",
        type: "strength",
        description: "An isolation machine for targeting the chest muscles through a fly motion.",
        // image: require("../assets/exercises/pec-deck.png"),
        muscleGroups: ["chest"],
        difficulty: "beginner",
    },
    {
        name: "Cable Rope Face Pull",
        type: "strength",
        description: "An upper-back and shoulder exercise performed with a rope on the cable machine.",
        // image: require("../assets/exercises/rope-face-pull.png"),
        muscleGroups: ["shoulders", "upper back"],
        difficulty: "beginner",
    },
    {
        name: "Standing Calf Raise Machine",
        type: "strength",
        description: "A machine-based exercise to isolate the calf muscles.",
        // image: require("../assets/exercises/standing-calf-raise.png"),
        muscleGroups: ["calves"],
        difficulty: "beginner",
    },
    {
        name: "Landmine Press",
        type: "strength",
        description: "A compound pressing exercise using a barbell anchored at one end.",
        // image: require("../assets/exercises/landmine-press.png"),
        muscleGroups: ["shoulders", "triceps", "core"],
        difficulty: "intermediate",
    },
    {
        name: "Cable Woodchopper",
        type: "strength",
        description: "A rotational core exercise using a cable machine.",
        // image: require("../assets/exercises/cable-woodchopper.png"),
        muscleGroups: ["core", "obliques"],
        difficulty: "intermediate",
    },
    {
        name: "Reverse Pec Deck (Rear Delt Fly)",
        type: "strength",
        description: "An isolation exercise for the rear deltoids using the pec deck machine in reverse.",
        // image: require("../assets/exercises/reverse-pec-deck.png"),
        muscleGroups: ["shoulders", "upper back"],
        difficulty: "beginner",
    },
    {
        name: "Cable Kickbacks",
        type: "strength",
        description: "An isolation glute exercise using the ankle strap on a cable machine.",
        // image: require("../assets/exercises/cable-kickbacks.png"),
        muscleGroups: ["glutes"],
        difficulty: "intermediate",
    },
    {
        name: "Farmer’s Carry",
        type: "strength",
        description: "A functional full-body exercise involving walking while carrying heavy weights.",
        // image: require("../assets/exercises/farmers-carry.png"),
        muscleGroups: ["forearms", "traps", "core"],
        difficulty: "intermediate",
    },
    {
        name: "Trap Bar Deadlift",
        type: "strength",
        description: "A variation of the deadlift using a hex bar that reduces lower back strain.",
        // image: require("../assets/exercises/trap-bar-deadlift.png"),
        muscleGroups: ["legs", "glutes", "back"],
        difficulty: "intermediate",
    },
    {
        name: "Incline Chest Press Machine",
        type: "strength",
        description: "A machine-based chest press done at an incline to emphasize the upper chest.",
        // image: require("../assets/exercises/incline-press-machine.png"),
        muscleGroups: ["chest", "shoulders", "triceps"],
        difficulty: "beginner",
    },
    {
        name: "Kettlebell Goblet Squat",
        type: "strength",
        description: "A squat performed holding a kettlebell in front of the chest, targeting the lower body and core.",
        // image: require("../assets/exercises/goblet-squat.png"),
        muscleGroups: ["legs", "glutes", "core"],
        difficulty: "beginner",
    },
];