
export const icons = {
  // Tab bar icons - not using
  // home: require("../assets/tabBarIcons/home.png"),
  // progress: require("../assets/tabBarIcons/progress.png"),
  // dumbbell: require("../assets/tabBarIcons/dumbbell.png"),
  // list: require("../assets/icons/list.png"),
  // friends: require("../assets/tabBarIcons/friends.png"),

  // Onboarding - not using
  // appleIconWhite: require("../assets/onboarding/appleIconWhite.png"),
  // figureHoldingBarbell: require("../assets/onboarding/figureHoldingBarbell.png"),
  // figureOneWeight: require("../assets/onboarding/figureOneWeight.png"),
  // figureOnPhoneDark: require("../assets/onboarding/figureOnPhoneDark.png"),
  // figureOnPhoneLight: require("../assets/onboarding/figureOnPhoneLight.png"),
  // figureRaceStart: require("../assets/onboarding/figureRaceStart.png"),
  // figuresHighFive: require("../assets/onboarding/figuresHighFive.png"),
  // figureTwoWeights: require("../assets/onboarding/figureTwoWeights.png"),
  // firstOnboardingImage: require("../assets/onboarding/firstOnboardingImage.png"),
  // googleIcon: require("../assets/onboarding/googleIcon.png"),

  // Icons - outdated
  // aiSparkle: require("../assets/icons/aiSparkle.png"),
  // carrotArrow: require("../assets/icons/carrotArrow.png"),
  // check: require("../assets/icons/check.png"),
  // clock: require("../assets/icons/clock.png"),
  // doubleCheck: require("../assets/icons/doubleCheck.png"),
  // dropdown: require("../assets/icons/dropdown.png"),
  // eye: require("../assets/icons/eye.png"),
  // female: require("../assets/icons/female.png"),
  // file: require("../assets/icons/file.png"),
  // greyX: require("../assets/icons/greyX.png"),
  // hamburger: require("../assets/icons/hamburger.png"),
  // history: require("../assets/icons/history.png"),
  // hollowClock: require("../assets/icons/hollowClock.png"),
  // keyboard: require("../assets/icons/keyboard.png"),
  // lightBulb: require("../assets/icons/lightBulb.png"),
  // listIcon: require("../assets/icons/list.png"), // renamed since you also have tabBar list
  // lock: require("../assets/icons/lock.png"),
  // male: require("../assets/icons/male.png"),
  // noEye: require("../assets/icons/noEye.png"),
  // noImage: require("../assets/icons/noimage.png"),
  // party: require("../assets/icons/party.png"),
  // pencil: require("../assets/icons/pencil.png"),
  // playCircle: require("../assets/icons/playCircle.png"),
  // plus: require("../assets/icons/plus.png"),
  // profileIcon: require("../assets/icons/profileIcon.png"),
  // remove: require("../assets/icons/remove.png"),
  // rightArrow: require("../assets/icons/rightArrow.png"),
  // rightCarrot: require("../assets/icons/rightCarrot.png"),
  // rotate: require("../assets/icons/rotate.png"),
  // scheduleRotationArrow: require("../assets/icons/scheduleRotationArrow.png"),
  // scheduleRotationArrowLength: require("../assets/icons/scheduleRotationArrowLength.png"),
  // search: require("../assets/icons/search.png"),
  // threeEllipses: require("../assets/icons/threeEllipses.png"),
  // trash: require("../assets/icons/trash.png"),
  // userHollow: require("../assets/icons/userHollow.png"),
  // weight: require("../assets/icons/weight.png"),
  // whiteRunner: require("../assets/icons/whiteRunner.png"),
  // whiteX: require("../assets/icons/whiteX.png"),

  // Emojis - using!
  coolEmoji: require("../assets/emojis/cool.png"),
  laughEmoji: require("../assets/emojis/laugh.png"),
  surprisedEmoji: require("../assets/emojis/surprised.png"),
  winkEmoji: require("../assets/emojis/wink.png"),
  heartEmoji: require("../assets/emojis/heart.png"),
  fireEmoji: require("../assets/emojis/fire.png"),
  hundredEmoji: require("../assets/emojis/hundred.png"),
  goatEmoji: require("../assets/emojis/goat.png"),
  gemEmoji: require("../assets/emojis/gem.png"),
  moneyEmoji: require("../assets/emojis/money.png"),
  holeEmoji: require("../assets/emojis/hole.png"),
  demonEmoji: require("../assets/emojis/demon.png"),
  progressEmoji: require("../assets/emojis/progress.png"),
  trophyEmoji: require("../assets/emojis/trophy.png"),
  starEmoji: require("../assets/emojis/star.png"),
  nophoneEmoji: require("../assets/emojis/nophone.png"),
  eyesEmoji: require("../assets/emojis/eyes.png"),
  showerEmoji: require("../assets/emojis/shower.png"),
  toiletEmoji: require("../assets/emojis/toilet.png"),
  beerEmoji: require("../assets/emojis/beer.png"),
  bicepEmoji: require("../assets/emojis/bicep.png"),

  // Food icons - using!
  fooddoodles1: require("../assets/food/fooddoodles1.svg"),
  fooddoodles2: require("../assets/food/fooddoodles2.svg"),
  fooddoodles3: require("../assets/food/fooddoodles3.svg"),
  fooddoodles4: require("../assets/food/fooddoodles4.svg"),
  fooddoodles5: require("../assets/food/fooddoodles5.svg"),
  fooddoodles6: require("../assets/food/fooddoodles6.svg"),
  fooddoodles7: require("../assets/food/fooddoodles7.svg"),
  fooddoodles8: require("../assets/food/fooddoodles8.svg"),
  fooddoodles9: require("../assets/food/fooddoodles9.svg"),
  fooddoodles10: require("../assets/food/fooddoodles10.svg"),
  fooddoodles11: require("../assets/food/fooddoodles11.svg"),
  fooddoodles12: require("../assets/food/fooddoodles12.svg"),
  fooddoodles13: require("../assets/food/fooddoodles13.svg"),
  fooddoodles14: require("../assets/food/fooddoodles14.svg"),
  fooddoodles15: require("../assets/food/fooddoodles15.svg"),
  fooddoodles16: require("../assets/food/fooddoodles16.svg"),
  fooddoodles17: require("../assets/food/fooddoodles17.svg"),
  fooddoodles18: require("../assets/food/fooddoodles18.svg"),
  fooddoodles19: require("../assets/food/fooddoodles19.svg"),
  fooddoodles20: require("../assets/food/fooddoodles20.svg"),
  fooddoodles21: require("../assets/food/fooddoodles21.svg"),
  fooddoodles22: require("../assets/food/fooddoodles22.svg"),
  fooddoodles23: require("../assets/food/fooddoodles23.svg"),
  fooddoodles24: require("../assets/food/fooddoodles24.svg"),
  fooddoodles25: require("../assets/food/fooddoodles25.svg"),
  fooddoodles26: require("../assets/food/fooddoodles26.svg"),
  fooddoodles27: require("../assets/food/fooddoodles27.svg"),
  fooddoodles28: require("../assets/food/fooddoodles28.svg"),
  fooddoodles29: require("../assets/food/fooddoodles29.svg"),
  fooddoodles30: require("../assets/food/fooddoodles30.svg"),
  fooddoodles31: require("../assets/food/fooddoodles31.svg"),
  fooddoodles32: require("../assets/food/fooddoodles32.svg"),
  fooddoodles33: require("../assets/food/fooddoodles33.svg"),
  fooddoodles34: require("../assets/food/fooddoodles34.svg"),
  fooddoodles35: require("../assets/food/fooddoodles35.svg"),
  fooddoodles36: require("../assets/food/fooddoodles36.svg"),
  fooddoodles37: require("../assets/food/fooddoodles37.svg"),
  fooddoodles38: require("../assets/food/fooddoodles38.svg"),
  fooddoodles39: require("../assets/food/fooddoodles39.svg"),
  fooddoodles40: require("../assets/food/fooddoodles40.svg"),
  fooddoodles41: require("../assets/food/fooddoodles41.svg"),
  fooddoodles42: require("../assets/food/fooddoodles42.svg"),
  fooddoodles43: require("../assets/food/fooddoodles43.svg"),
  fooddoodles44: require("../assets/food/fooddoodles44.svg"),
  fooddoodles45: require("../assets/food/fooddoodles45.svg"),
  fooddoodles46: require("../assets/food/fooddoodles46.svg"),
  fooddoodles47: require("../assets/food/fooddoodles47.svg"),
  fooddoodles48: require("../assets/food/fooddoodles48.svg"),
  fooddoodles49: require("../assets/food/fooddoodles49.svg"),
  fooddoodles50: require("../assets/food/fooddoodles50.svg"),
  fooddoodles51: require("../assets/food/fooddoodles51.svg"),
  fooddoodles52: require("../assets/food/fooddoodles52.svg"),
  fooddoodles53: require("../assets/food/fooddoodles53.svg"),
  fooddoodles54: require("../assets/food/fooddoodles54.svg"),
  fooddoodles55: require("../assets/food/fooddoodles55.svg"),
  fooddoodles56: require("../assets/food/fooddoodles56.svg"),
  fooddoodles57: require("../assets/food/fooddoodles57.svg"),
  fooddoodles58: require("../assets/food/fooddoodles58.svg"),
  fooddoodles59: require("../assets/food/fooddoodles59.svg"),
  fooddoodles60: require("../assets/food/fooddoodles60.svg"),
  fooddoodles61: require("../assets/food/fooddoodles61.svg"),
  fooddoodles62: require("../assets/food/fooddoodles62.svg"),
  fooddoodles63: require("../assets/food/fooddoodles63.svg"),
  fooddoodles64: require("../assets/food/fooddoodles64.svg"),
  fooddoodles65: require("../assets/food/fooddoodles65.svg"),
  fooddoodles66: require("../assets/food/fooddoodles66.svg"),
  fooddoodles67: require("../assets/food/fooddoodles67.svg"),
  fooddoodles68: require("../assets/food/fooddoodles68.svg"),
  fooddoodles69: require("../assets/food/fooddoodles69.svg"),
  fooddoodles70: require("../assets/food/fooddoodles70.svg"),
  fooddoodles71: require("../assets/food/fooddoodles71.svg"),
  fooddoodles72: require("../assets/food/fooddoodles72.svg"),
  fooddoodles73: require("../assets/food/fooddoodles73.svg"),
  fooddoodles74: require("../assets/food/fooddoodles74.svg"),
  fooddoodles75: require("../assets/food/fooddoodles75.svg"),
  fooddoodles76: require("../assets/food/fooddoodles76.svg"),
  fooddoodles77: require("../assets/food/fooddoodles77.svg"),
  fooddoodles78: require("../assets/food/fooddoodles78.svg"),
  fooddoodles79: require("../assets/food/fooddoodles79.svg"),
  fooddoodles80: require("../assets/food/fooddoodles80.svg"),
  fooddoodles81: require("../assets/food/fooddoodles81.svg"),
  fooddoodles82: require("../assets/food/fooddoodles82.svg"),
  fooddoodles83: require("../assets/food/fooddoodles83.svg"),
  fooddoodles84: require("../assets/food/fooddoodles84.svg"),
  fooddoodles85: require("../assets/food/fooddoodles85.svg"),
  fooddoodles86: require("../assets/food/fooddoodles86.svg"),
  fooddoodles87: require("../assets/food/fooddoodles87.svg"),
  fooddoodles88: require("../assets/food/fooddoodles88.svg"),
  fooddoodles89: require("../assets/food/fooddoodles89.svg"),
  fooddoodles90: require("../assets/food/fooddoodles90.svg"),
  fooddoodles91: require("../assets/food/fooddoodles91.svg"),
  fooddoodles92: require("../assets/food/fooddoodles92.svg"),
  fooddoodles93: require("../assets/food/fooddoodles93.svg"),
  fooddoodles94: require("../assets/food/fooddoodles94.svg"),
  fooddoodles95: require("../assets/food/fooddoodles95.svg"),
  fooddoodles96: require("../assets/food/fooddoodles96.svg"),
  fooddoodles97: require("../assets/food/fooddoodles97.svg"),
  fooddoodles98: require("../assets/food/fooddoodles98.svg"),
  fooddoodles99: require("../assets/food/fooddoodles99.svg"),
  fooddoodles100: require("../assets/food/fooddoodles100.svg"),
  fooddoodles101: require("../assets/food/fooddoodles101.svg"),
  fooddoodles102: require("../assets/food/fooddoodles102.svg"),
  fooddoodles103: require("../assets/food/fooddoodles103.svg"),
  fooddoodles104: require("../assets/food/fooddoodles104.svg"),
  fooddoodles105: require("../assets/food/fooddoodles105.svg"),
  fooddoodles106: require("../assets/food/fooddoodles106.svg"),
  fooddoodles107: require("../assets/food/fooddoodles107.svg"),
  fooddoodles108: require("../assets/food/fooddoodles108.svg"),
  fooddoodles109: require("../assets/food/fooddoodles109.svg"),
  fooddoodles110: require("../assets/food/fooddoodles110.svg"),
  fooddoodles111: require("../assets/food/fooddoodles111.svg"),
  fooddoodles112: require("../assets/food/fooddoodles112.svg"),
  fooddoodles113: require("../assets/food/fooddoodles113.svg"),
  fooddoodles114: require("../assets/food/fooddoodles114.svg"),
  fooddoodles115: require("../assets/food/fooddoodles115.svg"),
  fooddoodles116: require("../assets/food/fooddoodles116.svg"),
  fooddoodles117: require("../assets/food/fooddoodles117.svg"),
  fooddoodles118: require("../assets/food/fooddoodles118.svg"),
  fooddoodles119: require("../assets/food/fooddoodles119.svg"),
  fooddoodles120: require("../assets/food/fooddoodles120.svg"),
  fooddoodles121: require("../assets/food/fooddoodles121.svg"),
  fooddoodles122: require("../assets/food/fooddoodles122.svg"),
  fooddoodles123: require("../assets/food/fooddoodles123.svg"),
  fooddoodles124: require("../assets/food/fooddoodles124.svg"),
  fooddoodles125: require("../assets/food/fooddoodles125.svg"),
  fooddoodles126: require("../assets/food/fooddoodles126.svg"),
  fooddoodles127: require("../assets/food/fooddoodles127.svg"),
  fooddoodles128: require("../assets/food/fooddoodles128.svg"),
  fooddoodles129: require("../assets/food/fooddoodles129.svg"),
  fooddoodles130: require("../assets/food/fooddoodles130.svg"),
  fooddoodles131: require("../assets/food/fooddoodles131.svg"),
  fooddoodles132: require("../assets/food/fooddoodles132.svg"),
  fooddoodles133: require("../assets/food/fooddoodles133.svg"),
  fooddoodles134: require("../assets/food/fooddoodles134.svg"),
  fooddoodles135: require("../assets/food/fooddoodles135.svg"),
  fooddoodles136: require("../assets/food/fooddoodles136.svg"),
  fooddoodles137: require("../assets/food/fooddoodles137.svg"),
  fooddoodles138: require("../assets/food/fooddoodles138.svg"),
  fooddoodles139: require("../assets/food/fooddoodles139.svg"),
  fooddoodles140: require("../assets/food/fooddoodles140.svg"),
  fooddoodles141: require("../assets/food/fooddoodles141.svg"),
  fooddoodles142: require("../assets/food/fooddoodles142.svg"),
  fooddoodles143: require("../assets/food/fooddoodles143.svg"),
  fooddoodles144: require("../assets/food/fooddoodles144.svg"),
  fooddoodles145: require("../assets/food/fooddoodles145.svg"),
  fooddoodles146: require("../assets/food/fooddoodles146.svg"),
  fooddoodles147: require("../assets/food/fooddoodles147.svg"),
  fooddoodles148: require("../assets/food/fooddoodles148.svg"),
  fooddoodles149: require("../assets/food/fooddoodles149.svg"),
  fooddoodles150: require("../assets/food/fooddoodles150.svg"),
  fooddoodles151: require("../assets/food/fooddoodles151.svg"),
  fooddoodles152: require("../assets/food/fooddoodles152.svg"),
  fooddoodles153: require("../assets/food/fooddoodles153.svg"),
  fooddoodles154: require("../assets/food/fooddoodles154.svg"),
  fooddoodles155: require("../assets/food/fooddoodles155.svg"),
  fooddoodles156: require("../assets/food/fooddoodles156.svg"),
  fooddoodles157: require("../assets/food/fooddoodles157.svg"),
  fooddoodles158: require("../assets/food/fooddoodles158.svg"),
  fooddoodles159: require("../assets/food/fooddoodles159.svg"),
  fooddoodles160: require("../assets/food/fooddoodles160.svg"),
  fooddoodles161: require("../assets/food/fooddoodles161.svg"),
  fooddoodles162: require("../assets/food/fooddoodles162.svg"),
  fooddoodles163: require("../assets/food/fooddoodles163.svg"),
  fooddoodles164: require("../assets/food/fooddoodles164.svg"),
  fooddoodles165: require("../assets/food/fooddoodles165.svg"),
  fooddoodles166: require("../assets/food/fooddoodles166.svg"),
  fooddoodles167: require("../assets/food/fooddoodles167.svg"),
  fooddoodles168: require("../assets/food/fooddoodles168.svg"),
  fooddoodles169: require("../assets/food/fooddoodles169.svg"),
  fooddoodles170: require("../assets/food/fooddoodles170.svg"),
  fooddoodles171: require("../assets/food/fooddoodles171.svg"),
  fooddoodles172: require("../assets/food/fooddoodles172.svg"),
  fooddoodles173: require("../assets/food/fooddoodles173.svg"),
  fooddoodles174: require("../assets/food/fooddoodles174.svg"),
  fooddoodles175: require("../assets/food/fooddoodles175.svg"),
  fooddoodles176: require("../assets/food/fooddoodles176.svg"),
  fooddoodles177: require("../assets/food/fooddoodles177.svg"),
  fooddoodles178: require("../assets/food/fooddoodles178.svg"),
  fooddoodles179: require("../assets/food/fooddoodles179.svg"),
  fooddoodles180: require("../assets/food/fooddoodles180.svg"),
  fooddoodles181: require("../assets/food/fooddoodles181.svg"),
  fooddoodles182: require("../assets/food/fooddoodles182.svg"),
  fooddoodles183: require("../assets/food/fooddoodles183.svg"),
  fooddoodles184: require("../assets/food/fooddoodles184.svg"),
  fooddoodles185: require("../assets/food/fooddoodles185.svg"),
  fooddoodles186: require("../assets/food/fooddoodles186.svg"),
  fooddoodles187: require("../assets/food/fooddoodles187.svg"),
  fooddoodles188: require("../assets/food/fooddoodles188.svg"),
  fooddoodles189: require("../assets/food/fooddoodles189.svg"),
  fooddoodles190: require("../assets/food/fooddoodles190.svg"),
  fooddoodles191: require("../assets/food/fooddoodles191.svg"),
  fooddoodles192: require("../assets/food/fooddoodles192.svg"),
  fooddoodles193: require("../assets/food/fooddoodles193.svg"),
  fooddoodles194: require("../assets/food/fooddoodles194.svg"),
  fooddoodles195: require("../assets/food/fooddoodles195.svg"),
  fooddoodles196: require("../assets/food/fooddoodles196.svg"),
  fooddoodles197: require("../assets/food/fooddoodles197.svg"),
  fooddoodles198: require("../assets/food/fooddoodles198.svg"),
  fooddoodles199: require("../assets/food/fooddoodles199.svg"),
  fooddoodles200: require("../assets/food/fooddoodles200.svg"),
  fooddoodles201: require("../assets/food/fooddoodles201.svg"),
  fooddoodles202: require("../assets/food/fooddoodles202.svg"),
  fooddoodles203: require("../assets/food/fooddoodles203.svg"),
  fooddoodles204: require("../assets/food/fooddoodles204.svg"),
  fooddoodles205: require("../assets/food/fooddoodles205.svg"),
  fooddoodles206: require("../assets/food/fooddoodles206.svg"),
  fooddoodles207: require("../assets/food/fooddoodles207.svg"),
  fooddoodles208: require("../assets/food/fooddoodles208.svg"),
  fooddoodles209: require("../assets/food/fooddoodles209.svg"),
  fooddoodles210: require("../assets/food/fooddoodles210.svg"),
  fooddoodles211: require("../assets/food/fooddoodles211.svg"),
  fooddoodles212: require("../assets/food/fooddoodles212.svg"),
  fooddoodles213: require("../assets/food/fooddoodles213.svg"),
  fooddoodles214: require("../assets/food/fooddoodles214.svg"),
  fooddoodles215: require("../assets/food/fooddoodles215.svg"),
  fooddoodles216: require("../assets/food/fooddoodles216.svg"),
  fooddoodles217: require("../assets/food/fooddoodles217.svg"),
  fooddoodles218: require("../assets/food/fooddoodles218.svg"),
  fooddoodles219: require("../assets/food/fooddoodles219.svg"),
  fooddoodles220: require("../assets/food/fooddoodles220.svg"),
  fooddoodles221: require("../assets/food/fooddoodles221.svg"),
  fooddoodles222: require("../assets/food/fooddoodles222.svg"),
  fooddoodles223: require("../assets/food/fooddoodles223.svg"),
  fooddoodles224: require("../assets/food/fooddoodles224.svg"),
  fooddoodles225: require("../assets/food/fooddoodles225.svg"),
  fooddoodles226: require("../assets/food/fooddoodles226.svg"),
  fooddoodles227: require("../assets/food/fooddoodles227.svg"),
  fooddoodles228: require("../assets/food/fooddoodles228.svg"),
  fooddoodles229: require("../assets/food/fooddoodles229.svg"),
  fooddoodles230: require("../assets/food/fooddoodles230.svg"),
  fooddoodles231: require("../assets/food/fooddoodles231.svg"),
  fooddoodles232: require("../assets/food/fooddoodles232.svg"),
  fooddoodles233: require("../assets/food/fooddoodles233.svg"),
  fooddoodles234: require("../assets/food/fooddoodles234.svg"),
  fooddoodles235: require("../assets/food/fooddoodles235.svg"),
  fooddoodles236: require("../assets/food/fooddoodles236.svg"),
  fooddoodles237: require("../assets/food/fooddoodles237.svg"),
  fooddoodles238: require("../assets/food/fooddoodles238.svg"),
  fooddoodles239: require("../assets/food/fooddoodles239.svg"),
  fooddoodles240: require("../assets/food/fooddoodles240.svg"),
  fooddoodles241: require("../assets/food/fooddoodles241.svg"),
  fooddoodles242: require("../assets/food/fooddoodles242.svg"),
  fooddoodles243: require("../assets/food/fooddoodles243.svg"),
  fooddoodles244: require("../assets/food/fooddoodles244.svg"),
  fooddoodles245: require("../assets/food/fooddoodles245.svg"),
  fooddoodles246: require("../assets/food/fooddoodles246.svg"),
  fooddoodles247: require("../assets/food/fooddoodles247.svg"),
  fooddoodles248: require("../assets/food/fooddoodles248.svg"),
  fooddoodles249: require("../assets/food/fooddoodles249.svg"),
  fooddoodles250: require("../assets/food/fooddoodles250.svg"),
  fooddoodles251: require("../assets/food/fooddoodles251.svg"),
  fooddoodles252: require("../assets/food/fooddoodles252.svg"),
  fooddoodles253: require("../assets/food/fooddoodles253.svg"),
  fooddoodles254: require("../assets/food/fooddoodles254.svg"),
  fooddoodles255: require("../assets/food/fooddoodles255.svg"),
  fooddoodles256: require("../assets/food/fooddoodles256.svg"),
  fooddoodles257: require("../assets/food/fooddoodles257.svg"),
  fooddoodles258: require("../assets/food/fooddoodles258.svg"),
  fooddoodles259: require("../assets/food/fooddoodles259.svg"),
  fooddoodles260: require("../assets/food/fooddoodles260.svg"),
  fooddoodles261: require("../assets/food/fooddoodles261.svg"),
  fooddoodles262: require("../assets/food/fooddoodles262.svg"),
  fooddoodles263: require("../assets/food/fooddoodles263.svg"),
  fooddoodles264: require("../assets/food/fooddoodles264.svg"),
  fooddoodles265: require("../assets/food/fooddoodles265.svg"),
  fooddoodles266: require("../assets/food/fooddoodles266.svg"),
  fooddoodles267: require("../assets/food/fooddoodles267.svg"),
  fooddoodles268: require("../assets/food/fooddoodles268.svg"),
  fooddoodles269: require("../assets/food/fooddoodles269.svg"),
  fooddoodles270: require("../assets/food/fooddoodles270.svg"),
  fooddoodles271: require("../assets/food/fooddoodles271.svg"),
  fooddoodles272: require("../assets/food/fooddoodles272.svg"),
  fooddoodles273: require("../assets/food/fooddoodles273.svg"),
  fooddoodles274: require("../assets/food/fooddoodles274.svg"),
  fooddoodles275: require("../assets/food/fooddoodles275.svg"),
  fooddoodles276: require("../assets/food/fooddoodles276.svg"),
  fooddoodles277: require("../assets/food/fooddoodles277.svg"),
  fooddoodles278: require("../assets/food/fooddoodles278.svg"),
  fooddoodles279: require("../assets/food/fooddoodles279.svg"),
  fooddoodles280: require("../assets/food/fooddoodles280.svg"),
  fooddoodles281: require("../assets/food/fooddoodles281.svg"),
  fooddoodles282: require("../assets/food/fooddoodles282.svg"),
  fooddoodles283: require("../assets/food/fooddoodles283.svg"),
  fooddoodles284: require("../assets/food/fooddoodles284.svg"),
  fooddoodles285: require("../assets/food/fooddoodles285.svg"),
  fooddoodles286: require("../assets/food/fooddoodles286.svg"),
  fooddoodles287: require("../assets/food/fooddoodles287.svg"),
  fooddoodles288: require("../assets/food/fooddoodles288.svg"),
  fooddoodles289: require("../assets/food/fooddoodles289.svg"),
  fooddoodles290: require("../assets/food/fooddoodles290.svg"),
  fooddoodles291: require("../assets/food/fooddoodles291.svg"),
  fooddoodles292: require("../assets/food/fooddoodles292.svg"),
  fooddoodles293: require("../assets/food/fooddoodles293.svg"),
  fooddoodles294: require("../assets/food/fooddoodles294.svg"),
  fooddoodles295: require("../assets/food/fooddoodles295.svg"),
  fooddoodles296: require("../assets/food/fooddoodles296.svg"),
  fooddoodles297: require("../assets/food/fooddoodles297.svg"),
  fooddoodles298: require("../assets/food/fooddoodles298.svg"),
  fooddoodles299: require("../assets/food/fooddoodles299.svg"),
  fooddoodles300: require("../assets/food/fooddoodles300.svg"),
  fooddoodles301: require("../assets/food/fooddoodles301.svg"),
  fooddoodles302: require("../assets/food/fooddoodles302.svg"),
  fooddoodles303: require("../assets/food/fooddoodles303.svg"),
  fooddoodles304: require("../assets/food/fooddoodles304.svg"),
  fooddoodles305: require("../assets/food/fooddoodles305.svg"),
  fooddoodles306: require("../assets/food/fooddoodles306.svg"),
  fooddoodles307: require("../assets/food/fooddoodles307.svg"),
  fooddoodles308: require("../assets/food/fooddoodles308.svg"),
  fooddoodles309: require("../assets/food/fooddoodles309.svg"),
  fooddoodles310: require("../assets/food/fooddoodles310.svg"),
  fooddoodles311: require("../assets/food/fooddoodles311.svg"),
  fooddoodles312: require("../assets/food/fooddoodles312.svg"),
  fooddoodles313: require("../assets/food/fooddoodles313.svg"),
  fooddoodles314: require("../assets/food/fooddoodles314.svg"),
  fooddoodles315: require("../assets/food/fooddoodles315.svg"),
  fooddoodles316: require("../assets/food/fooddoodles316.svg"),
  fooddoodles317: require("../assets/food/fooddoodles317.svg"),
  fooddoodles318: require("../assets/food/fooddoodles318.svg"),
  fooddoodles319: require("../assets/food/fooddoodles319.svg"),
  fooddoodles320: require("../assets/food/fooddoodles320.svg"),
  fooddoodles321: require("../assets/food/fooddoodles321.svg"),
  fooddoodles322: require("../assets/food/fooddoodles322.svg"),
  fooddoodles323: require("../assets/food/fooddoodles323.svg"),
  fooddoodles324: require("../assets/food/fooddoodles324.svg"),
  fooddoodles325: require("../assets/food/fooddoodles325.svg"),
  fooddoodles326: require("../assets/food/fooddoodles326.svg"),
  fooddoodles327: require("../assets/food/fooddoodles327.svg"),
  fooddoodles328: require("../assets/food/fooddoodles328.svg"),
  fooddoodles329: require("../assets/food/fooddoodles329.svg"),
  fooddoodles330: require("../assets/food/fooddoodles330.svg"),
  fooddoodles331: require("../assets/food/fooddoodles331.svg"),
  fooddoodles332: require("../assets/food/fooddoodles332.svg"),
  fooddoodles333: require("../assets/food/fooddoodles333.svg"),
  fooddoodles334: require("../assets/food/fooddoodles334.svg"),
  fooddoodles335: require("../assets/food/fooddoodles335.svg"),
  fooddoodles336: require("../assets/food/fooddoodles336.svg"),
  fooddoodles337: require("../assets/food/fooddoodles337.svg"),
  fooddoodles338: require("../assets/food/fooddoodles338.svg"),
  fooddoodles339: require("../assets/food/fooddoodles339.svg"),
  fooddoodles340: require("../assets/food/fooddoodles340.svg"),
  fooddoodles341: require("../assets/food/fooddoodles341.svg"),
  fooddoodles342: require("../assets/food/fooddoodles342.svg"),
  fooddoodles343: require("../assets/food/fooddoodles343.svg"),
  fooddoodles344: require("../assets/food/fooddoodles344.svg"),
  fooddoodles345: require("../assets/food/fooddoodles345.svg"),
  fooddoodles346: require("../assets/food/fooddoodles346.svg"),
  fooddoodles347: require("../assets/food/fooddoodles347.svg"),
  fooddoodles348: require("../assets/food/fooddoodles348.svg"),
  fooddoodles349: require("../assets/food/fooddoodles349.svg"),
  fooddoodles350: require("../assets/food/fooddoodles350.svg"),
  fooddoodles351: require("../assets/food/fooddoodles351.svg"),
  fooddoodles352: require("../assets/food/fooddoodles352.svg"),
  fooddoodles353: require("../assets/food/fooddoodles353.svg"),
  fooddoodles354: require("../assets/food/fooddoodles354.svg"),
  fooddoodles355: require("../assets/food/fooddoodles355.svg"),
};

export const iconArray = Object.values(icons);