export const SuggestedWorkouts = [
   {
      "exercises":[
         {
            "id":"1",
            "sets":[
               {
                  "uniqueId":"mj92xmt9-a5eelrl3",
                  "weight":"",
                  "reps":"6"
               },
               {
                  "uniqueId":"mj92xn6c-zifjlmc1",
                  "weight":"",
                  "reps":"6"
               },
               {
                  "uniqueId":"mj92xnhy-kwzekhod",
                  "weight":"",
                  "reps":"6"
               },
               {
                  "uniqueId":"mj92xnsi-z97ltx6c",
                  "weight":"",
                  "reps":"6"
               }
            ],
            "name":"Barbell Bench Press",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"chest",
            "uniqueId":"mj92q0qi-0ldlu1rs"
         },
         {
            "id":"22",
            "sets":[
               {
                  "uniqueId":"mj92xssa-m6dxedlh",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj92xvek-zye4c4c9",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj92xvse-vro19v8u",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj92xw82-qdccursz",
                  "weight":"",
                  "reps":"8"
               }
            ],
            "name":"Cable Lat Pulldown",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"back",
            "uniqueId":"mj92q0qi-f4pjzyye"
         },
         {
            "id":"54",
            "sets":[
               {
                  "uniqueId":"mj92y1ar-teyg3csc",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj92y1kj-jqmtvsfn",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj92y1w7-b2dcqypx",
                  "weight":"",
                  "reps":"10"
               }
            ],
            "name":"Dumbbell Shoulder Press",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"shoulder",
            "uniqueId":"mj92q0qi-ov191mk9"
         },
         {
            "id":"25",
            "sets":[
               {
                  "uniqueId":"mj92y99t-6ag42rcs",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj92y9l6-00a9y577",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj92yaif-gn31qtrz",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj92ycs7-2q62stkm",
                  "weight":"",
                  "reps":"8"
               }
            ],
            "name":"Barbell Bent-Over Row",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"back",
            "uniqueId":"mj92q0qi-wlxzdwci"
         },
         {
            "id":"32",
            "sets":[
               {
                  "uniqueId":"mj92ygbj-3c288zr4",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj92ygsf-k4sf6niy",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj92yh6a-wu6vzh9g",
                  "weight":"",
                  "reps":"12"
               }
            ],
            "name":"Dumbbell Bicep Curl",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"bicep",
            "uniqueId":"mj92q0qj-qoo4iv4p"
         },
         {
            "id":"42",
            "sets":[
               {
                  "uniqueId":"mj975xh7-bimaj3f2",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj975xuo-9ryyxllg",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj975y8d-r1rrpva7",
                  "weight":"",
                  "reps":"8"
               }
            ],
            "name":"Dip",
            "unit":"imperial",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"tricep",
            "uniqueId":"mj92q0qj-zkl25fsj"
         },
         {
            "id":"13",
            "sets":[
               {
                  "uniqueId":"mj975oaj-osdgmffb",
                  "time":"0.75"
               },
               {
                  "uniqueId":"mj97mmyf-n0vbwvyd",
                  "time":"0.75"
               },
               {
                  "uniqueId":"mj97mnws-r0io6m1q",
                  "time":"0.75"
               }
            ],
            "name":"Plank",
            "unit":"metric",
            "tracks":[
               "time"
            ],
            "group":"abs",
            "uniqueId":"mj931sva-a6mx66un"
         }
      ],
      "id":"mj92muxe-2rzboi23",
      "name":"Upper Body Strength"
   },
   {
      "exercises":[
         {
            "id":"58",
            "sets":[
               {
                  "uniqueId":"mj980mdc-55ixi4xx",
                  "weight":"",
                  "reps":"6"
               },
               {
                  "uniqueId":"mj980n28-xtqk14gr",
                  "weight":"",
                  "reps":"6"
               },
               {
                  "uniqueId":"mj980nsa-j7h2zu0m",
                  "weight":"",
                  "reps":"6"
               },
               {
                  "uniqueId":"mj980o74-qksakv2x",
                  "weight":"",
                  "reps":"6"
               }
            ],
            "name":"Barbell Squat",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"leg",
            "uniqueId":"mj92vuc4-jl1qiq53"
         },
         {
            "id":"21",
            "sets":[
               {
                  "uniqueId":"mj980t9c-7s71hf7i",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj980uma-tojm4za5",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj980vks-b2zxltgb",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj980w4p-xg4uvi8l",
                  "weight":"",
                  "reps":"8"
               }
            ],
            "name":"Barbell Deadlift",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"back",
            "uniqueId":"mj92vuc4-q3lx22hi"
         },
         {
            "id":"65",
            "sets":[
               {
                  "uniqueId":"mj98107m-0pczqb8f",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj9810k3-dvrnorg5",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj9810xq-iryhnart",
                  "weight":"",
                  "reps":"12"
               }
            ],
            "name":"Dumbbell Lunge",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"leg",
            "uniqueId":"mj92vuc4-buw29hmq"
         },
         {
            "id":"61",
            "sets":[
               {
                  "uniqueId":"mj981jb4-x2b5bzjg",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj981jn2-fn5nrcjd",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj981k10-ccg09en7",
                  "weight":"",
                  "reps":"10"
               }
            ],
            "name":"Machine Leg Press",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"leg",
            "uniqueId":"mj92vuc4-hcbrpxzy"
         },
         {
            "id":"63",
            "sets":[
               {
                  "uniqueId":"mj981q0k-1za47yle",
                  "weight":"",
                  "reps":"15"
               },
               {
                  "uniqueId":"mj981ra5-gotwi7x6",
                  "weight":"",
                  "reps":"15"
               },
               {
                  "uniqueId":"mj981rri-1v4tu6lc",
                  "weight":"",
                  "reps":"15"
               }
            ],
            "name":"Machine Calf Raise",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"leg",
            "uniqueId":"mj92vuc4-jpc6jcx7"
         },
         {
            "id":"18",
            "sets":[
               {
                  "uniqueId":"mj9820kq-57xw82uv",
                  "weight":"",
                  "reps":"25"
               },
               {
                  "uniqueId":"mj98210n-tq54do1p",
                  "weight":"",
                  "reps":"25"
               },
               {
                  "uniqueId":"mj98222o-xc3x8d6x",
                  "weight":"",
                  "reps":"25"
               }
            ],
            "name":"Sit-Up",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"abs",
            "uniqueId":"mj92vuc4-4ih0a3bz"
         },
         {
            "id":"60",
            "sets":[
               {
                  "uniqueId":"mj982nb4-1qqd53ep",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj982noq-z42lt9kh",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj982o57-kh8rp0x3",
                  "weight":"",
                  "reps":"12"
               }
            ],
            "name":"Machine Leg Extensions",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"leg",
            "uniqueId":"mj92vuc4-4x6x9wxa"
         }
      ],
      "id":"mj92tm1x-5y53i316",
      "name":"Lower Body Power"
   },
   {
      "exercises":[
         {
            "id":"54",
            "sets":[
               {
                  "uniqueId":"mj98578h-y7t3ftlt",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj9857m8-dczszvy5",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj9858o3-524mfxp8",
                  "weight":"",
                  "reps":"12"
               }
            ],
            "name":"Dumbbell Shoulder Press",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"shoulder",
            "uniqueId":"mj9855cj-xo5io2p4"
         },
         {
            "id":"52",
            "sets":[
               {
                  "uniqueId":"mj985bns-rdenm6c0",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj985c0s-8swf729m",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj985cew-r5o8jkic",
                  "weight":"",
                  "reps":"12"
               }
            ],
            "name":"Dumbbell Lateral Raise",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"shoulder",
            "uniqueId":"mj9855cj-m8a6ntq4"
         },
         {
            "id":"27",
            "sets":[
               {
                  "uniqueId":"mj985fue-d09dpf0x",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj985gnz-p8ucid4m",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj985h4b-7brae5y1",
                  "weight":"",
                  "reps":"12"
               }
            ],
            "name":"Cable Rope Face Pull",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"back",
            "uniqueId":"mj9855cj-he94w8pm"
         },
         {
            "id":"23",
            "sets":[
               {
                  "uniqueId":"mj985jro-kmlans52",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj985k81-hqus1flf",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj985kp8-f8hel58a",
                  "weight":"",
                  "reps":"10"
               }
            ],
            "name":"Cable Seated Row",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"back",
            "uniqueId":"mj9855cj-h0wbi137"
         },
         {
            "id":"57",
            "sets":[
               {
                  "uniqueId":"mj985rtc-06kuiop6",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj985s9q-y4i1stl3",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj985u1p-yjjaysyo",
                  "weight":"",
                  "reps":"10"
               }
            ],
            "name":"Machine Deltoid Raise",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"shoulder",
            "uniqueId":"mj9855cj-mnpsvqfd"
         },
         {
            "id":"28",
            "sets":[
               {
                  "uniqueId":"mj985xa6-808sizql",
                  "weight":"",
                  "reps":"15"
               },
               {
                  "uniqueId":"mj985xpb-gn44k52f",
                  "weight":"",
                  "reps":"15"
               },
               {
                  "uniqueId":"mj985y34-opwrjbr4",
                  "weight":"",
                  "reps":"15"
               }
            ],
            "name":"Dumbbell Shoulder Shrug",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"back",
            "uniqueId":"mj9855cj-xyg4e6qy"
         }
      ],
      "id":"mj983m3k-6v5ijzm6",
      "name":"Shoulder Sculpt"
   },
   {
      "exercises":[
         {
            "id":"33",
            "sets":[
               {
                  "uniqueId":"mj989wrd-92qrc698",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj989x4b-styhn8im",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj989xih-ori69mga",
                  "weight":"",
                  "reps":"10"
               }
            ],
            "name":"Barbell Curl",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"bicep",
            "uniqueId":"mj989urg-esh23i8t"
         },
         {
            "id":"41",
            "sets":[
               {
                  "uniqueId":"mj98a050-nsh7wuc2",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98a0hl-skpdvf5u",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98a0w2-sxrze09p",
                  "weight":"",
                  "reps":"10"
               }
            ],
            "name":"Cable Tricep Pushdown",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"tricep",
            "uniqueId":"mj989urg-x6p3ko72"
         },
         {
            "id":"34",
            "sets":[
               {
                  "uniqueId":"mj98a3d6-wxcwqolo",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj98a3u0-59n8cf76",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj98a5hw-bvpuqwi4",
                  "weight":"",
                  "reps":"12"
               }
            ],
            "name":"Dumbbell Hammer Curl",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"bicep",
            "uniqueId":"mj989urg-ouj2dirn"
         },
         {
            "id":"43",
            "sets":[
               {
                  "uniqueId":"mj98ajxg-0frkyet1",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98akbe-c5kv1ggn",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98akrq-0s7ax7w2",
                  "weight":"",
                  "reps":"10"
               }
            ],
            "name":"Cable Overhead Tricep Extension",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"tricep",
            "uniqueId":"mj989urg-c7lxnbju"
         },
         {
            "id":"38",
            "sets":[
               {
                  "uniqueId":"mj98atlg-ncjmgzmr",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98atyg-bjpsjzla",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98aujv-wh2pj5ca",
                  "weight":"",
                  "reps":"10"
               }
            ],
            "name":"Barbell Preacher Curl",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"bicep",
            "uniqueId":"mj989urg-7pa2k68d"
         }
      ],
      "id":"mj98696u-10ll10an",
      "name":"Arm Definition"
   },
   {
      "exercises":[
         {
            "id":"1",
            "sets":[
               {
                  "uniqueId":"mj98e915-zlr6btcy",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj98e9pp-co5do6hf",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj98ea4y-n9o0qukd",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj98eamn-ugfz15fb",
                  "weight":"",
                  "reps":"8"
               }
            ],
            "name":"Barbell Bench Press",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"chest",
            "uniqueId":"mj98e6sr-e45gtkwy"
         },
         {
            "id":"5",
            "sets":[
               {
                  "uniqueId":"mj98edwj-4b5eyw5u",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98eea2-9ctqyerz",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98eepd-zfbcqzbd",
                  "weight":"",
                  "reps":"10"
               }
            ],
            "name":"Incline Dumbbell Bench Press",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"chest",
            "uniqueId":"mj98e6sr-05wwqg74"
         },
         {
            "id":"10",
            "sets":[
               {
                  "uniqueId":"mj98eho4-0584mq0w",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj98eij1-b8xc5sc2",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj98eiyy-jyntt5ww",
                  "weight":"",
                  "reps":"12"
               }
            ],
            "name":"Dumbbell Fly",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"chest",
            "uniqueId":"mj98e6sr-52io7ao8"
         },
         {
            "id":"42",
            "sets":[
               {
                  "uniqueId":"mj98elkc-71v3kydq",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj98emtz-zwwzj1yh",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj98en8u-t1csk48c",
                  "weight":"",
                  "reps":"12"
               }
            ],
            "name":"Dip",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"tricep",
            "uniqueId":"mj98e6sr-rlpm4c9j"
         },
         {
            "id":"41",
            "sets":[
               {
                  "uniqueId":"mj98erd0-orf7lw37",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj98ert5-9n3cnj7d",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj98esen-d46ldg0w",
                  "weight":"",
                  "reps":"12"
               }
            ],
            "name":"Cable Tricep Pushdown",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"tricep",
            "uniqueId":"mj98e6sr-0jdpu3bt"
         },
         {
            "id":"48",
            "sets":[
               {
                  "uniqueId":"mj98evti-ppsblyrt",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98ew5z-e7ez6zc3",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98ewkk-gqfck1ww",
                  "weight":"",
                  "reps":"10"
               }
            ],
            "name":"Barbell Skull Crusher",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"tricep",
            "uniqueId":"mj98e6sr-ngwbzjqj"
         }
      ],
      "id":"mj98bgsx-rm7k1phw",
      "name":"Chest & Triceps"
   },
   {
      "exercises":[
         {
            "id":"21",
            "sets":[
               {
                  "uniqueId":"mj98gt2b-7ju8ylht",
                  "weight":"",
                  "reps":"6"
               },
               {
                  "uniqueId":"mj98gtyj-998ar94z",
                  "weight":"",
                  "reps":"6"
               },
               {
                  "uniqueId":"mj98guci-1dhv1x0s",
                  "weight":"",
                  "reps":"6"
               },
               {
                  "uniqueId":"mj98gult-p3obrglb",
                  "weight":"",
                  "reps":"6"
               }
            ],
            "name":"Barbell Deadlift",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"back",
            "uniqueId":"mj98gr8z-ltizmm0f"
         },
         {
            "id":"26",
            "sets":[
               {
                  "uniqueId":"mj98gy43-yb7aallz",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj98gysf-j0ts27lj",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj98gzp0-3l84st5g",
                  "weight":"",
                  "reps":"8"
               },
               {
                  "uniqueId":"mj98h076-24vqa9fl",
                  "weight":"",
                  "reps":"8"
               }
            ],
            "name":"Pull-Up",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"back",
            "uniqueId":"mj98gr8z-yzfictzl"
         },
         {
            "id":"23",
            "sets":[
               {
                  "uniqueId":"mj98h3x3-jot3p14p",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98h4s8-qqkizf3w",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98h59d-ce248xz6",
                  "weight":"",
                  "reps":"10"
               }
            ],
            "name":"Cable Seated Row",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"back",
            "uniqueId":"mj98gr8z-2kml78rm"
         },
         {
            "id":"24",
            "sets":[
               {
                  "uniqueId":"mj98h8w0-ij2fugui",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98h9jq-nct3erev",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98h9xl-qc2tr675",
                  "weight":"",
                  "reps":"10"
               }
            ],
            "name":"Dumbbell One-Arm Row",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"back",
            "uniqueId":"mj98gr8z-dwmkt76k"
         },
         {
            "id":"33",
            "sets":[
               {
                  "uniqueId":"mj98hj4a-tziqh9on",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98hjk6-k2i5q6io",
                  "weight":"",
                  "reps":"10"
               },
               {
                  "uniqueId":"mj98hk06-kgrscdf3",
                  "weight":"",
                  "reps":"10"
               }
            ],
            "name":"Barbell Curl",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"bicep",
            "uniqueId":"mj98gr8z-0qrfosm4"
         },
         {
            "id":"38",
            "sets":[
               {
                  "uniqueId":"mj98hota-fvw4h5f2",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj98hp8y-go5wwsfl",
                  "weight":"",
                  "reps":"12"
               },
               {
                  "uniqueId":"mj98hpwz-zwjaz1bn",
                  "weight":"",
                  "reps":"12"
               }
            ],
            "name":"Barbell Preacher Curl",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"bicep",
            "uniqueId":"mj98gr8z-jpb7hmps"
         },
         {
            "id":"27",
            "sets":[
               {
                  "uniqueId":"mj98ht6n-29qk23m7",
                  "weight":"",
                  "reps":"15"
               },
               {
                  "uniqueId":"mj98hukh-o2lz7rd0",
                  "weight":"",
                  "reps":"15"
               },
               {
                  "uniqueId":"mj98huvz-1f18dyb6",
                  "weight":"",
                  "reps":"15"
               }
            ],
            "name":"Cable Rope Face Pull",
            "tracks":[
               "weight",
               "reps"
            ],
            "group":"back",
            "uniqueId":"mj98gr8z-kedh3xl3"
         }
      ],
      "id":"mj98f4i6-609k14yt",
      "name":"Back & Biceps"
   }
]